spring.application.name=examen-cvds
spring.data.mongodb.uri=mongodb+srv://danieldcamelo:cvds2025-1@cluster0.e1vyod9.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=cvds